### ISSUE TITLE
EPUB: 'Other Penguin Shorts' section should be separate file

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#16] opened 2012-07-24 14:03 UTC
Currently it is appended to Chapter 6, after the "imprint"/copyright page (see previous issue)

**Comment by nic-gibson** [comment] 2012-08-03 12:12
Probably caused by an unrecognised heading style.

**Comment by andrgosl** [comment] 2012-08-03 12:26
For the copyright page head we will use style 13 EM Head and for Body we will use 13 EM Endnotes FL. 
Andreas to confirm with Al.
Chris to modify style mapping CSS for this.

For by the same author text, Nic correct transformation based 01 FM By the same author head.

**Comment by nic-gibson** [comment] 2012-08-09 11:01
Should be fixed on the DocBook side.

**Comment by nic-gibson** [comment] 2012-08-14 21:54
Fixed in EPUB too

**Closed as completed by nic-gibson** 2012-08-14 21:54 UTC
